import * as React from "react";
import Head from "next/head";
import {
  Box,
  Button,
  CardMedia,
  Typography,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import { createStyles } from "@mui/material/styles";

const Main = () => {
  const theme = useTheme();
  const isTabletScreen = useMediaQuery(theme.breakpoints.down("800"));
  const isMobileScreen = useMediaQuery(theme.breakpoints.down("500"));

  const useStyles = createStyles(() => ({
    main: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      background:
        "linear-gradient(136.71deg, rgba(119, 209, 227, 0.18) 13.48%, rgba(158, 192, 244, 0.18) 85.14%);",
      width: "100%",
      height: "100vh",
      pt: "6rem",
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    btns: {
      display: "flex",
      flexDirection: isTabletScreen ? "column" : "row",
      alignItems: "center",
      mx: 2,
    },
    btn: {
      "&:hover": {
        background: "#ffffff",
      },
      background: "#ffffff",
      backdropFilter: "blur(46px)",
      borderRadius: "8px",
      fontStyle: "normal",
      fontWeight: "700",
      fontSize: isMobileScreen ? "14px" : "20px",
      color: "#000000",
      textTransform: "capitalize",
      py: 2,
      px: 5,
      width: isMobileScreen ? "100%" : "360px",
      border: "none",
    },
    icon: {
      mx: 1,
      color: "white",
      height: "17px",
      width: "22px",
    },
    header: {
      position: "relative",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      mb: 4,
    },
    vector: {
      width: isTabletScreen && "35px" && isMobileScreen ? "30px" : "35px",
      height: isTabletScreen && "35px" && isMobileScreen ? "30px" : "35px",
    },
    vectorLight: {
      position: "absolute",
      width: isTabletScreen && "78px" && isMobileScreen ? "60px" : "78px",
      height: isTabletScreen && "78px" && isMobileScreen ? "60px" : "78px",
      top: isMobileScreen ? "-65px" : "-70px",
      left: isMobileScreen ? "37px" : "30px",
    },
    sator: {
      width: isTabletScreen && "220px" && isMobileScreen ? "150px" : "220px",
      marginRight: isTabletScreen ? "1.5rem" : "4.7rem",
    },
    title: {
      fontWeight: "700",
      fontSize: "45px",
      ["@media (max-width:800px)"]: {
        fontSize: "30px",
      },
      ["@media (max-width:450px)"]: {
        fontSize: "18px",
      },
      mb: 4,
      textAlign: "center",
    },
    footer: {
      // background:
      //   "radial-gradient(37.58% 37.58% at 49.97% 0%, #9483FF 20%, rgba(198, 189, 255, 0) 100%)",
      height: "100vh",
      width: "100%",
      top: "330px",
      pt: 2,
      textAlign: "center",
      children: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        textAlign: "center",
        position: "relative",
      },
    },
    description: {
      width: isTabletScreen ? "100%" : "50rem",
      fontWeight: "400",
      fontSize: "20px",
      lineHeight: "27.32px",
      textAlign: "center",
    },
    ellipse: {
      height: "100vh",
      width: "130vw",
      borderRadius: "50%",
      position: "absolute",
      top: "30px",
      background:
        "radial-gradient(37.58% 37.58% at 49.97% 0%, #9483FF 20%, rgba(198, 189, 255, 0) 100%)",
      ["@media (max-width:800px)"]: {
        width: "170vw",
      },
      ["@media (max-width:450px)"]: {
        width: "250vw",
      },
    },
    btnStyle: {
      background:
        "linear-gradient(90.29deg, #5E5AFF 0%, #AD28FF 22.92%, #28E5FF 51.56%, #FF8F28 75.52%, #5E5AFF 100%)",
      padding: "5px",
      marginRight: isTabletScreen ? 0 : 3,
      zIndex: 100,
      borderRadius: "8px",
      padding: "3px",
      mb: 2,
    },
  }));
  const classes = useStyles();

  const icons = [
    { iconClass: "fa-youtube" },
    { iconClass: "fa-discord" },
    { iconClass: "fa-tiktok" },
    { iconClass: "fa-twitter" },
    { iconClass: "fa-instagram" },
  ];

  return (
    <React.Fragment>
      <Head>
        <title>Sator Web Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossOrigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <Box sx={classes.main}>
        <Box sx={classes.header}>
          <Box>
            <CardMedia
              component="img"
              image="/images/sator.png"
              alt="alternative"
              sx={classes.sator}
            />
          </Box>
          <Box
            sx={{
              position: "relative",
            }}
          >
            <CardMedia
              component="img"
              image="/images/vector.png"
              alt="alternative"
              sx={classes.vector}
            />
            <CardMedia
              component="img"
              image="/images/vector-light.png"
              alt="alternative"
              sx={classes.vectorLight}
            />
          </Box>
        </Box>
        <Typography sx={classes.title}>
          {isTabletScreen
            ? "Comprehensive web3 platform expanding linear content to metaverse"
            : "Web3 entertainment network"}
        </Typography>
        <Box sx={classes.footer}>
          <Box sx={classes.footer.children}>
            <Box sx={classes.ellipse}></Box>
            <Box sx={classes.btns}>
              {!isMobileScreen && (
                <Box sx={classes.btnStyle}>
                  <Button sx={classes.btn}>Download Sator App</Button>
                </Box>
              )}
              <Box sx={classes.btnStyle}>
                <Button sx={classes.btn}>Enter The NFT Marketplace</Button>
              </Box>
            </Box>
            <Box sx={{ py: 4, zIndex: 1 }}>
              {icons.map(({ iconClass }, i) => (
                <Box
                  component="i"
                  sx={classes.icon}
                  className={`fa-brands ${iconClass}`}
                  key={i}
                />
              ))}
            </Box>
            {!isMobileScreen ? (
              <Typography sx={classes.description}>
                The Sator platform aligns content ecosystem participants in an
                open economy that increases value creation and distribution
              </Typography>
            ) : null}
          </Box>
        </Box>
      </Box>
    </React.Fragment>
  );
};

export default Main;
